# Generated by Django 4.0.6 on 2022-07-09 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'It is not allowed to use negative numbers'), django.core.validators.MaxValueValidator(4, 'The max qualification for a restaurant is 4')], verbose_name='Rating of the restaurant')),
                ('name', models.CharField(max_length=64, verbose_name='Name of the restaurant')),
                ('site', models.CharField(max_length=255, verbose_name='Web site of the restaurant')),
                ('email', models.CharField(max_length=62, verbose_name='Email of the restaurant')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone of the restaurant')),
                ('street', models.CharField(max_length=35, verbose_name='Street where is located the restaurant')),
                ('city', models.CharField(max_length=35, verbose_name='City where is located the restaurant')),
                ('state', models.CharField(max_length=35, verbose_name='State where is located the restaurant')),
                ('lat', models.FloatField(verbose_name='Latitude of the location of the restaurant')),
                ('lng', models.FloatField(verbose_name='Longitude of the location of the restaurant')),
            ],
        ),
    ]
